#!/bin/bash

# This script copies Let's Encrypt certificates generated by Certbot 
# into the project's certs/ directory and sets the correct permissions.

DOMAIN=$1

if [ -z "$DOMAIN" ]; then
  echo "Usage: ./use-certbot.sh <your-domain>"
  echo "Example: ./use-certbot.sh mqtt.meshgw.com"
  exit 1
fi

LE_PATH="/etc/letsencrypt/live/$DOMAIN"

if [ ! -d "$LE_PATH" ]; then
  echo "Error: Let's Encrypt path not found: $LE_PATH"
  echo "Make sure you have run certbot for this domain first."
  exit 1
fi

echo "--- Copying certificates for $DOMAIN ---"

# Copy files
# chain.pem -> ca.crt (Intermediate CA)
# fullchain.pem -> server.crt (Server cert + chain)
# privkey.pem -> server.key (Private key)
sudo cp "$LE_PATH/chain.pem" certs/ca.crt
sudo cp "$LE_PATH/fullchain.pem" certs/server.crt
sudo cp "$LE_PATH/privkey.pem" certs/server.key

# Set permissions for Mosquitto (UID 1883)
# Note: Mosquitto requires the key to be owned by the user running it or root with strict permissions.
# Since we run Mosquitto as UID 1883, we set ownership here.
sudo chown 1883:1883 certs/ca.crt certs/server.crt certs/server.key
sudo chmod 644 certs/ca.crt certs/server.crt
sudo chmod 600 certs/server.key

echo "--- Success: Certificates copied to certs/ ---"
echo "You can now start/restart the broker with: docker-compose restart mqtt-broker"
